blueprint:
name: Zigbee2MQTT - Tuya 1-Button Scene Switch V01.2025
description: Automate your Tuya 1-Button Scene Switch via Zigbee2MQTT.
domain: automation
input:
switch:
name: Tuya 1-Button Scene Switch
description: Tuya 1-Button Scene Switch to use
selector:
device:
integration: mqtt

button_one_short_press:
  name: Single Press - Button 1
  description: Action to run on button 1 (lower-left) single press
  default: []
  selector:
    action: {}
button_one_double_press:
  name: Double Press - Button 1
  description: Action to run on button 1 (lower-left) double press
  default: []
  selector:
    action: {}
button_one_long_press:
  name: Long Press - Button 1
  description: Action to run on button 1 (lower-left) long press
  default: []
  selector:
    action: {}
trigger:
	- platform: device
		device_id: !input switch
		domain: mqtt
		type: action
		subtype: single
	- platform: device
		device_id: !input switch
		domain: mqtt
		type: action
		subtype: double
	- platform: device
		device_id: !input switch
		domain: mqtt
		type: action
		subtype: hold

action:
- variables:
	command: '{{ trigger.payload }}'
- choose:
	- conditions: '{{ command == ''single'' }}'
		sequence: !input button_one_short_press
	- conditions: '{{ command == ''double'' }}'
		sequence: !input button_one_double_press
	- conditions: '{{ command == ''hold'' }}'
		sequence: !input button_one_long_press
